# Generated by Django 5.2.6 on 2025-10-10 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0002_profile_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="profiles/%Y/%m/%d"
            ),
        ),
    ]
