# Generated by Django 5.2.6 on 2025-11-02 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0003_profile_bio_profile_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
    ]
