# Generated by Django 5.2.6 on 2025-11-07 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0004_profile_is_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="nutricionista",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "nutricionista"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alunos_nutricionista",
                to="profile.profile",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="personal",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "personal"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alunos_personal",
                to="profile.profile",
            ),
        ),
    ]
