# Generated by Django 5.2.6 on 2025-11-07 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0005_profile_nutricionista_profile_personal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="nutricionista",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role__iexact": "nutricionista"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alunos_nutricionista",
                to="profile.profile",
                verbose_name="Nutricionista",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="personal",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role__iexact": "personal"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alunos_personal",
                to="profile.profile",
                verbose_name="Personal Trainer",
            ),
        ),
    ]
