# Generated by Django 5.2.6 on 2025-09-27 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('aluno', 'Aluno'), ('personal', 'Personal'), ('nutricionista', 'Nutricionista'), ('admin', 'Administrador')], default='aluno', max_length=20),
        ),
    ]
